import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './content/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        background: '#051424',
        'on-background': '#d4e4fa',
        surface: '#051424',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#c2c6d6',
        'surface-container': '#122131',
        'surface-container-low': '#0d1c2d',
        'surface-container-high': '#1c2b3c',
        'surface-container-lowest': '#010f1f',
        'surface-container-highest': '#273647',
        'surface-variant': '#273647',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-tint': '#adc6ff',
        outline: '#8c909f',
        'outline-variant': '#424754',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        secondary: '#bec6e0',
        'on-secondary': '#283044',
        'secondary-container': '#3f465c',
        tertiary: '#bcc7de',
        'on-tertiary': '#263143',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'inverse-primary': '#005ac2',
        'secondary-fixed-dim': '#bec6e0',
        'on-tertiary-container': '#1f2a3c',
        'primary-fixed': '#d8e2ff',
        'tertiary-container': '#8691a7',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed': '#131b2e',
        'tertiary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary-container': '#adb4ce',
        'tertiary-fixed-dim': '#bcc7de',
        'on-secondary-fixed-variant': '#3f465c',
        'on-primary-fixed': '#001a42',
        'secondary-fixed': '#dae2fd',
        'on-tertiary-fixed-variant': '#3c475a',
        'on-tertiary-fixed': '#111c2d',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-sm': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'mono-label': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-label': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
